name: Updating registry

on:
    push:
      branches: [ main ]
      paths-ignore:
        - "*.json"
    schedule:
      - cron:  '30 20 * * 5'

permissions:
  contents: write
  id-token: write

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - run: npm i node-fetch node-html-parser

            - name: Download registry
              run: node .github/workflows/orgs.js

            - name: Commit update
              run: |
                set +e
                git add registry.json -f
                git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
                git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
                git commit -m "Update registry"
                git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"